### ISSUE TITLE
Catkin Build Error: "No packages were found in the source space"

### ISSUE THREAD

**Issue by sszxc** [ethz-asl/active_grasp#3]
When attempting to use the "catkin build" command, I received the error message: "No packages were found in the source space." I have not been successful in resolving the problem. Could you please provide some guidance or assistance on how to proceed?

```
~/Documents/active_grasp$ catkin build active_grasp
------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/noetic
Workspace:                   /home/henrik/Documents/active_grasp
------------------------------------------------------------------------
Build Space:        [exists] /home/henrik/Documents/active_grasp/build
Devel Space:        [exists] /home/henrik/Documents/active_grasp/devel
Install Space:      [unused] /home/henrik/Documents/active_grasp/install
Log Space:          [exists] /home/henrik/Documents/active_grasp/logs
Source Space:       [exists] /home/henrik/Documents/active_grasp/src
DESTDIR:            [unused] None
------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------
[build] No packages were found in the source space '/home/henrik/Documents/active_grasp/src'
[build] Error: Given package 'active_grasp' is not in the workspace and pattern does not match any package
```

**Comment by Twilight89** [comment]
Hi, same problem

**Comment by Twilight89** [comment]
> When attempting to use the "catkin build" command, I received the error message: "No packages were found in the source space." I have not been successful in resolving the problem. Could you please provide some guidance or assistance on how to proceed?
> 
> ```
> ~/Documents/active_grasp$ catkin build active_grasp
> ------------------------------------------------------------------------
> Profile:                     default
> Extending:             [env] /opt/ros/noetic
> Workspace:                   /home/henrik/Documents/active_grasp
> ------------------------------------------------------------------------
> Build Space:        [exists] /home/henrik/Documents/active_grasp/build
> Devel Space:        [exists] /home/henrik/Documents/active_grasp/devel
> Install Space:      [unused] /home/henrik/Documents/active_grasp/install
> Log Space:          [exists] /home/henrik/Documents/active_grasp/logs
> Source Space:       [exists] /home/henrik/Documents/active_grasp/src
> DESTDIR:            [unused] None
> ------------------------------------------------------------------------
> Devel Space Layout:          linked
> Install Space Layout:        None
> ------------------------------------------------------------------------
> Additional CMake Args:       None
> Additional Make Args:        None
> Additional catkin Make Args: None
> Internal Make Job Server:    True
> Cache Job Environments:      False
> ------------------------------------------------------------------------
> Buildlisted Packages:        None
> Skiplisted Packages:         None
> ------------------------------------------------------------------------
> Workspace configuration appears valid.
> ------------------------------------------------------------------------
> [build] No packages were found in the source space '/home/henrik/Documents/active_grasp/src'
> [build] Error: Given package 'active_grasp' is not in the workspace and pattern does not match any package
> ```

Solve this. You are supposed to place this repo in catkin_ws/src.

**Comment by sszxc** [comment]
> > When attempting to use the "catkin build" command, I received the error message: "No packages were found in the source space." I have not been successful in resolving the problem. Could you please provide some guidance or assistance on how to proceed?
> > ```
> > ~/Documents/active_grasp$ catkin build active_grasp
> > ------------------------------------------------------------------------
> > Profile:                     default
> > Extending:             [env] /opt/ros/noetic
> > Workspace:                   /home/henrik/Documents/active_grasp
> > ------------------------------------------------------------------------
> > Build Space:        [exists] /home/henrik/Documents/active_grasp/build
> > Devel Space:        [exists] /home/henrik/Documents/active_grasp/devel
> > Install Space:      [unused] /home/henrik/Documents/active_grasp/install
> > Log Space:          [exists] /home/henrik/Documents/active_grasp/logs
> > Source Space:       [exists] /home/henrik/Documents/active_grasp/src
> > DESTDIR:            [unused] None
> > ------------------------------------------------------------------------
> > Devel Space Layout:          linked
> > Install Space Layout:        None
> > ------------------------------------------------------------------------
> > Additional CMake Args:       None
> > Additional Make Args:        None
> > Additional catkin Make Args: None
> > Internal Make Job Server:    True
> > Cache Job Environments:      False
> > ------------------------------------------------------------------------
> > Buildlisted Packages:        None
> > Skiplisted Packages:         None
> > ------------------------------------------------------------------------
> > Workspace configuration appears valid.
> > ------------------------------------------------------------------------
> > [build] No packages were found in the source space '/home/henrik/Documents/active_grasp/src'
> > [build] Error: Given package 'active_grasp' is not in the workspace and pattern does not match any package
> > ```
> 
> Solve this. You are supposed to place this repo in catkin_ws/src.

Thank you for your help. I made a silly little mistake 🤣

**Comment by Twilight89** [comment]
> > > When attempting to use the "catkin build" command, I received the error message: "No packages were found in the source space." I have not been successful in resolving the problem. Could you please provide some guidance or assistance on how to proceed?
> > > ```
> > > ~/Documents/active_grasp$ catkin build active_grasp
> > > ------------------------------------------------------------------------
> > > Profile:                     default
> > > Extending:             [env] /opt/ros/noetic
> > > Workspace:                   /home/henrik/Documents/active_grasp
> > > ------------------------------------------------------------------------
> > > Build Space:        [exists] /home/henrik/Documents/active_grasp/build
> > > Devel Space:        [exists] /home/henrik/Documents/active_grasp/devel
> > > Install Space:      [unused] /home/henrik/Documents/active_grasp/install
> > > Log Space:          [exists] /home/henrik/Documents/active_grasp/logs
> > > Source Space:       [exists] /home/henrik/Documents/active_grasp/src
> > > DESTDIR:            [unused] None
> > > ------------------------------------------------------------------------
> > > Devel Space Layout:          linked
> > > Install Space Layout:        None
> > > ------------------------------------------------------------------------
> > > Additional CMake Args:       None
> > > Additional Make Args:        None
> > > Additional catkin Make Args: None
> > > Internal Make Job Server:    True
> > > Cache Job Environments:      False
> > > ------------------------------------------------------------------------
> > > Buildlisted Packages:        None
> > > Skiplisted Packages:         None
> > > ------------------------------------------------------------------------
> > > Workspace configuration appears valid.
> > > ------------------------------------------------------------------------
> > > [build] No packages were found in the source space '/home/henrik/Documents/active_grasp/src'
> > > [build] Error: Given package 'active_grasp' is not in the workspace and pattern does not match any package
> > > ```
> > 
> > 
> > Solve this. You are supposed to place this repo in catkin_ws/src.
> 
> Thank you for your help. I made a silly little mistake 🤣

Hhhhh. Did you finish the reproduction of this repo in the simulation? I meet some problems when I tried to repro. Could we add a social communication software like WeChat for discussing?

**Comment by sszxc** [comment]
> > > > When attempting to use the "catkin build" command, I received the error message: "No packages were found in the source space." I have not been successful in resolving the problem. Could you please provide some guidance or assistance on how to proceed?
> > > > ```
> > > > ~/Documents/active_grasp$ catkin build active_grasp
> > > > ------------------------------------------------------------------------
> > > > Profile:                     default
> > > > Extending:             [env] /opt/ros/noetic
> > > > Workspace:                   /home/henrik/Documents/active_grasp
> > > > ------------------------------------------------------------------------
> > > > Build Space:        [exists] /home/henrik/Documents/active_grasp/build
> > > > Devel Space:        [exists] /home/henrik/Documents/active_grasp/devel
> > > > Install Space:      [unused] /home/henrik/Documents/active_grasp/install
> > > > Log Space:          [exists] /home/henrik/Documents/active_grasp/logs
> > > > Source Space:       [exists] /home/henrik/Documents/active_grasp/src
> > > > DESTDIR:            [unused] None
> > > > ------------------------------------------------------------------------
> > > > Devel Space Layout:          linked
> > > > Install Space Layout:        None
> > > > ------------------------------------------------------------------------
> > > > Additional CMake Args:       None
> > > > Additional Make Args:        None
> > > > Additional catkin Make Args: None
> > > > Internal Make Job Server:    True
> > > > Cache Job Environments:      False
> > > > ------------------------------------------------------------------------
> > > > Buildlisted Packages:        None
> > > > Skiplisted Packages:         None
> > > > ------------------------------------------------------------------------
> > > > Workspace configuration appears valid.
> > > > ------------------------------------------------------------------------
> > > > [build] No packages were found in the source space '/home/henrik/Documents/active_grasp/src'
> > > > [build] Error: Given package 'active_grasp' is not in the workspace and pattern does not match any package
> > > > ```
> > > 
> > > 
> > > Solve this. You are supposed to place this repo in catkin_ws/src.
> > 
> > 
> > Thank you for your help. I made a silly little mistake 🤣
> 
> Hhhhh. Did you finish the reproduction of this repo in the simulation? I meet some problems when I tried to repro. Could we add a social communication software like WeChat for discussing?

I have indeed encountered some difficulties... You can raise them in another issue, and I will see if I can provide assistance maybe? It also make it easier for other friends in need to see.
